### ISSUE TITLE
[TensorRT] ERROR: Network must have at least one output

### ISSUE THREAD

**Issue by suiato** [tsutof/tiny_yolov2_onnx_cam#6]
$ python3 tiny_yolov2_onnx_cam.py ---camera=-1
issues the error:
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.

I'm using JetPack4.3 on Jetson Nano Developer Kit (old original version) with a CSI camera.

Following is the record at the terminal:
nano@nano:~/tiny_yolov2_onnx_cam$ python3 tiny_yolov2_onnx_cam.py --camera=-1
GST_ARGUS: Creating output stream
CONSUMER: Waiting until producer is connected...
GST_ARGUS: Available Sensor modes :
GST_ARGUS: 3264 x 2464 FR = 21.000000 fps Duration = 47619048 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 3264 x 1848 FR = 28.000001 fps Duration = 35714284 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1920 x 1080 FR = 29.999999 fps Duration = 33333334 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 59.999999 fps Duration = 16666667 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: 1280 x 720 FR = 120.000005 fps Duration = 8333333 ; Analog Gain range min 1.000000, max 10.625000; Exposure Range min 13000, max 683709000;

GST_ARGUS: Running with following settings:
   Camera index = 0 
   Camera mode  = 4 
   Output Stream W = 1280 H = 720 
   seconds to Run    = 0 
   Frame Rate = 120.000005 
GST_ARGUS: Setup Complete, Starting captures for 0 seconds
GST_ARGUS: Starting repeat capture requests.
CONSUMER: Producer has connected; continuing.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1

Download from https://raw.githubusercontent.com/pjreddie/darknet/master/data/voc.names
100% [..............................................................] 135 / 135
Download from https://onnxzoo.blob.core.windows.net/models/opset_8/tiny_yolov2/tiny_yolov2.tar.gz
100% [....................................................] 60875831 / 60875831Loading ONNX file from path tiny_yolov2/Model.onnx...
Beginning ONNX file parsing
Completed parsing of ONNX file
Building an engine from file tiny_yolov2/Model.onnx; this may take a while...
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
Completed creating Engine
Traceback (most recent call last):
  File "tiny_yolov2_onnx_cam.py", line 261, in <module>
    main()
  File "tiny_yolov2_onnx_cam.py", line 196, in main
    with get_engine(onnx_file_path, engine_file_path) as engine, \
  File "/home/nano/tiny_yolov2_onnx_cam/get_engine.py", line 90, in get_engine
    return build_engine()
  File "/home/nano/tiny_yolov2_onnx_cam/get_engine.py", line 81, in build_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
GST_ARGUS: Cleaning up
CONSUMER: Done Success
GST_ARGUS: Done Success

(python3:27828): GStreamer-CRITICAL **: 13:26:22.249: gst_mini_object_set_qdata: assertion 'object != NULL' failed

**Comment by tsutof** [comment]
@suiato 
Thank you for your report.
I have installed my application from scratch with the same condition as yours today.

- Jetson Nano Dev Kit A02
- JetPack 4.3 SD card image

Then I have confirmed that it worked fine.

Would you please try again with the following steps and see if it works?

1. sudo nvpmodel -m 0
2. sudo jetson_clocks
3. rm model.trt
4. rm tiny_yolov2.tar.gz
5. python3 tiny_yolov2_onnx_cam.py --camera=-1

**Comment by suiato** [comment]
Thank you for your prompt reply. I followed the command sequence, and the error remained the same.
After some debugging, I found that the line 78:
`engine = builder.build_cuda_engine(network)`
returns None.

jetsonUtilities showed:
```
$ ./jetsonInfo.py 
 NVIDIA Jetson TX1
 L4T 32.4.2 [ JetPack UNKNOWN ]
 Ubuntu 18.04.4 LTS
 Kernel Version: 4.9.140-tegra
 CUDA 10.2.89
```
I wonder why it's JetsonTX1, and JetPack UNKNOWN...

**Comment by tsutof** [comment]
@suiato 
Thank you for the information. I found you are using JetPack 4.4DP and I conformed that my application does not work for the JetPack version. Now I'm debugging it. So please wait for while.

**Comment by suiato** [comment]
@tsutof 
Thank you for your message.  I'll appreciate your effort to resolve the issue.

Sorry about the version of JetPack. I misinterpreted the [JetPack page](https://developer.nvidia.com/embedded/jetpack) when downloading the image. Good to know it's 4.4 :)

**Comment by tsutof** [comment]
@suiato 
I have modified the source code (common.py, get_engine.py) to support TensorRT v7 and have changed the ONNX restriction in requirement.txt.
Would you please try the new version on your Jetson?
Thanks.

**Comment by suiato** [comment]
Yes, it **WORKED** beautifully :) 
Running around 10fps.

There's a warning:

> [ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
> Reading engine from file model.trt
> Gtk-Message: 16:50:16.347: Failed to load module "canberra-gtk-module"

Thank you so much for your effort.

**Comment by tfuru-macnica** [comment]
@suiato 
Thank you very much for your test.
For the Gtk-Message warning, the following command works to suppress the warning. But I don't know why it is needed.

`$ sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`

For OpenCV warning, I don't know how to fix it. Actually, OpenCV 4.1 which installed with the recent version of JetPack, does not work well on the camera query functions. But I remember that OpenCV 3.x worked fine on the query and didn't show the warning.

Thanks again for your report.

**Comment by tsutof** [comment]
@suiato
Thank you very much for your test.
For the Gtk-Message warning, the following command works to suppress the warning. But I don't know why it is needed.

`$ sudo apt install libcanberra-gtk-module libcanberra-gtk3-module`

For OpenCV warning, I don't know how to fix it. Actually, OpenCV 4.1 which installed with the recent version of JetPack, does not work well on the camera query functions. But I remember that OpenCV 3.x worked fine on the query and didn't show the warning.

Thanks again for your report.
